<a href="https://colab.research.google.com/github/PanciSaigo/PytorchRookie/blob/main/Pytorch_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch


In [ ]:
pip list

# TENSORS
*   A torch. Tensor is a multi-dimensional matrix containing elements of a single data type.

*   Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

*   default data type of float32.
*   More suitable for deep learning than a numpy array.

In [4]:
import torch
import numpy as np

# LIST

In [6]:
my_list = [1,2,3]
my_multiDimensionalArray = [[1,2,3,4,5],[1,2,3,4,5]]
my_list
my_multiDimensionalArray


[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]

# Numpy Array

In [9]:
np1 = np.random.rand(3,4)
np1



dtype('float64')

In [10]:

np1.dtype

dtype('float64')

In [11]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.5557,  0.4748,  0.0603,  1.0282],
        [ 0.0447, -0.8827, -0.5446, -1.0743],
        [-2.0967,  0.0751,  0.5261, -2.7634]])

In [13]:
tensor_3d  = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
##crete tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor


tensor([[0.0092, 0.2594, 0.6879, 0.5267],
        [0.7980, 0.6081, 0.9566, 0.7905],
        [0.8892, 0.5880, 0.5732, 0.7625]], dtype=torch.float64)

# Tensor Operation

In [19]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Reshape and View**

In [21]:
#reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
#reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch3 = torch.arange(15)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2
# attention the number of items with reshape need to be perfectely divided by reshaped request number ex: 15 items reshape in 3 is ok but in 2 is impossible

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [31]:
my_torch3 = my_torch3.reshape(-1,5)
my_torch3

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [34]:
#using view
my_torch4 = my_torch3.view(3,5)
my_torch4

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [ ]:
#differences betweeen reshape and view in pytorch
#https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch


In [39]:
#with reshape and view they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [43]:
#changing the my_torch5[1]
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [44]:
#updated!
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

**Slices**

In [45]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
#grab a specific item
my_torch7[7]

tensor(7)

In [47]:
#grab slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [49]:

my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [50]:
# return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

# Tensor Math Operation
*  Add, Subtract, Multiply, Divide, Remainders, Exponents
*  Shorthand and Longhand
*  Reassignment

In [52]:
tensor_a  = torch.tensor([1,2,3,4])
tensor_b  = torch.tensor([5,6,7,8])

In [53]:
# addition shorthand
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [64]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [54]:
# addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [55]:
# subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [56]:
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [57]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [58]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [59]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [60]:
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [61]:
# remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [62]:
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [63]:
# Exponents / Power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [65]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [66]:
tensor_a

tensor([1, 2, 3, 4])

In [68]:
#tensor_a = tensor_a + tensor_b  LONG WAY TO REASSIGN
tensor_a.add_(tensor_b)
tensor_a
#reassigned !

tensor([ 6,  8, 10, 12])

# Bsic Neural Network Model